### ISSUE TITLE
If lvm version not supported give error message

### ISSUE THREAD

**Issue by bbaugher** [gregsymons/di-ruby-lvm-attrib#19]
We recently ran into an issue where we were using an older version of this gem with a newer version of lvm that was not supported yet and saw this error message,

    Errno::ENOENT: No such file or directory - /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/di-ruby-lvm-attrib-0.0.14/lib/lvm/attributes/2.02.111(2)/lvs.yaml
    /opt/chef/embedded/lib/ruby/1.9.1/psych.rb:297:in `initialize'
    /opt/chef/embedded/lib/ruby/1.9.1/psych.rb:297:in `open'
    /opt/chef/embedded/lib/ruby/1.9.1/psych.rb:297:in `load_file'
    /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/di-ruby-lvm-attrib-0.0.14/lib/lvm/attributes.rb:20:in `load'

It would be great if this exception was caught and re-thrown with an error message saying that this version of LVM is not supported yet.

**Comment by gregsymons** [comment]
Actually... that's not a bad idea. I'll poke someone at DI to make sure that someone is watching, since I'm no longer there, and no longer have commit privileges. Send in a pull request for it if you can.
