### ISSUE TITLE
Attributes generated for LVM 2.0.2.115 invalid for di-ruby-lvm gem

### ISSUE THREAD

**Issue by lopaka** [gregsymons/di-ruby-lvm-attrib#22]
RHEL 7.1 and CentOS 7.1 uses LVM 2.02.115.  Using di-ruby-lvm initially fails with:
```
NoMethodError: undefined method `[]' for nil:NilClass
```

Investigation shows the attributes generated with `generate_field_data` is not handling the new `/lib/report/columns.h` file

**Comment by gregsymons** [comment]
Fixed by #23.
