### ISSUE TITLE
Can a new version of the gem be released?

### ISSUE THREAD

**Issue by st-isidore-de-seville** [gregsymons/di-ruby-lvm-attrib#32]
There was recently a new version of the LVM attributes: https://github.com/gregsymons/di-ruby-lvm-attrib/commit/066b18001f0fb75b21277e88fdc9d866dc173169 (#31) that fixes this gem to work with a recently updated version of LVM2 on RHEL7.  Thanks!

**Comment by gregsymons** [comment]
Version 0.0.22 has been pushed to rubygems. I don't have access to my signing key at the moment, so I haven't tagged it yet, but it's built off of @649c508, so it has the changes you're looking for. I'll close this request when I get it tagged.

**Comment by galley123** [comment]
Thanks for releasing 0.0.22!

**Comment by st-isidore-de-seville** [comment]
Thanks @gregsymons!

**Comment by bozinsky** [comment]
Thank you!

**Comment by gregsymons** [comment]
Since at this point, my old signing key is going to expire in two months anyway, I've generated a new key, and that will be used to sign releases going forward.
