### ISSUE TITLE
Tying di-ruby-lvm-attrib to major.minor.patch versions of LVM

### ISSUE THREAD

**Issue by st-isidore-de-seville** [gregsymons/di-ruby-lvm-attrib#33]
Recently I have experienced a situation whereby an upgrade to LVM2 in RHEL 7 broke compatibility with the LVM cookbook and subsequently this gem: https://github.com/gregsymons/di-ruby-lvm-attrib/issues/32

I am wondering if it is necessary to tie the attributes that this gem provides to the patched versions of LVM thus avoiding breaking changes when RHEL decides to release an updated version.  Basically for RHEL 6, RHEL 7, the major and minor version will always be locked but is there really a substantial difference in a patched version that would warrant a release of this gem every time.

Thanks in advance!

**Comment by gregsymons** [comment]
If there's *any* difference between the mappings in this gem and the LVM data structures, then the `di-ruby-lvm` library breaks. There's no upstream guarantee that there won't be changes, so, to be safe, we just regenerate the files for every version. Probably there is a lot of redundancy across the mapping files, but it works.

It'd be nice to come up with a better scheme, like maybe generating the mapping file during gem installation, and regenerating it on demand if an LVM upgrade is detected, but I don't actually use this gem myself any more, so I haven't really been spending any time on it. Pull requests are welcome, though :smile:
