### ISSUE TITLE
New release to support Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by maxvt** [gregsymons/di-ruby-lvm-attrib#48]
Hi, the most recent image of Xenial uses 2.02.133(2) which was only recently added in https://github.com/gregsymons/di-ruby-lvm-attrib/commit/5603b4018ea8458b540a3af1696079c9ece7fcd5 and is not included in 0.0.26. Please make a release so that this gem could be installed without having to go through Github. Thank you!

**Comment by JorisAndrade** [comment]
Yes support would be nice, any update on this ?

**Comment by glensc** [comment]
perhaps add to README.md a line how to use this gem from github git url?

i can merge such PR, but i can't publish the gem releases

**Comment by gregsymons** [comment]
0.0.27 has been released and pushed to rubygems. I apologize for the delay.
