### ISSUE TITLE
New release for RHEL 7.3 support

### ISSUE THREAD

**Issue by eheydrick** [gregsymons/di-ruby-lvm-attrib#53]
Can you release a new version. Support for 2.02.166(2) / RHEL 7.3 was added in #51 but has yet to be released.

**Comment by ryankoski-at-work** [comment]
Add us to the list of folks / companies waiting for this release. Thanks @gregsymons!

**Comment by tas50** [comment]
Just a heads up to anyone following this issue. Chef has forked both of these gems and released the contents of both master branches. The latest lvm chef cookbook will be using the newly forked gems found here:

https://github.com/chef/chef-ruby-lvm
https://github.com/chef/chef-ruby-lvm-attrib

**Comment by glensc** [comment]
@gregsymons perhaps just  transfer this whole repo including its infrastructure (tickets/PR's) to new maintainer. seems @chef is interested maintaining this.

**Comment by gregsymons** [comment]
Yep, I did.
